"""
Accounts storage: PostgreSQL when DATABASE_URL is set (Railway), SQLite otherwise
(local development). SQL is written once with "?" placeholders and kept to the
subset both engines share.
"""
import os
import sqlite3
from contextlib import contextmanager

DATABASE_URL = os.environ.get("DATABASE_URL", "")
IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))
SQLITE_PATH = os.environ.get("SQLITE_PATH", os.path.join("data", "glane.db"))

SCHEMA = [
    """CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        created_at BIGINT NOT NULL,
        last_login_at BIGINT
    )""",
    """CREATE TABLE IF NOT EXISTS login_tokens (
        token_hash TEXT PRIMARY KEY,
        email TEXT NOT NULL,
        expires_at BIGINT NOT NULL,
        used_at BIGINT
    )""",
    # Collections keep the id generated by the browser, so a guest's
    # collections can be uploaded unchanged at first sign-in.
    """CREATE TABLE IF NOT EXISTS collections (
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        id TEXT NOT NULL,
        name TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        updated_at BIGINT NOT NULL,
        cover_key TEXT,
        items TEXT NOT NULL,
        deleted INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY (user_id, id)
    )""",
    # "WTF flag" reports from visitors: candidates for app/backend/denylist.txt.
    """CREATE TABLE IF NOT EXISTS flags (
        faiss_id BIGINT PRIMARY KEY,
        reports INTEGER NOT NULL,
        last_at BIGINT NOT NULL
    )""",
]


class _DB:
    def __init__(self, con):
        self.con = con

    def execute(self, sql, params=()):
        if IS_POSTGRES:
            sql = sql.replace("?", "%s")
        return self.con.execute(sql, params)

    def one(self, sql, params=()):
        row = self.execute(sql, params).fetchone()
        return dict(row) if row else None

    def all(self, sql, params=()):
        return [dict(r) for r in self.execute(sql, params).fetchall()]


def _connect():
    if IS_POSTGRES:
        import psycopg
        from psycopg.rows import dict_row
        return psycopg.connect(DATABASE_URL, row_factory=dict_row)
    os.makedirs(os.path.dirname(SQLITE_PATH) or ".", exist_ok=True)
    con = sqlite3.connect(SQLITE_PATH, timeout=10)
    con.row_factory = sqlite3.Row
    con.execute("PRAGMA foreign_keys = ON")
    return con


@contextmanager
def transaction():
    con = _connect()
    try:
        yield _DB(con)
        con.commit()
    except Exception:
        con.rollback()
        raise
    finally:
        con.close()


def init():
    with transaction() as db:
        for statement in SCHEMA:
            db.execute(statement)
